# Generated by Django 4.0.5 on 2022-06-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=512)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
